language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t tejaspisal08/docker-react -f Dockerfile.dev .
    
script:
    - docker run tejaspisal08/docker-react npm run test -- --coverage